services:
  club_app: &app
    image: ghcr.io/moontechs/event-based-dating-platform:${TAG_VERSION:-latest}
    container_name: club_app
    networks:
      - club_network
    env_file:
      - .env
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./storage/app/public:/app/storage/app/public
    depends_on:
      - keydb
      - postgres
    ports:
      - "127.0.0.1:80:80"
      - "127.0.0.1:443:443"
    command: make docker-server-php
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

  club_queue:
    <<: *app
    container_name: club_queue
    command: make docker-server-queue
    ports: []
    healthcheck:
      test: [ "CMD-SHELL", "pgrep -f 'queue:work' > /dev/null || exit 1" ]
      interval: 60s
      timeout: 5s
      retries: 3
    depends_on:
      - keydb
      - postgres
      - club_app

  postgres:
    image: postgres:17
    container_name: club_postgres
    restart: unless-stopped
    user: "1000"
    env_file:
      - /home/deploy/database/.env
    volumes:
      - /home/deploy/database/data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - club_network
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

  keydb:
    image: eqalpha/keydb:latest
    container_name: club_keydb
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 60s
      timeout: 10s
      retries: 3
    ports:
      - "127.0.0.1:6379:6379"
    networks:
      - club_network
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

  fluentbit:
    image: fluent/fluent-bit:2.2
    container_name: club_fluentbit
    env_file:
      - /home/deploy/fluentbit/.env
    volumes:
      - /home/deploy/fluentbit/fluentbit.conf:/fluent-bit/etc/fluent-bit.conf:ro
      - /home/deploy/fluentbit/parsers.conf:/fluent-bit/etc/parsers.conf:ro
      - /home/deploy/fluentbit/container_enrichment.lua:/fluent-bit/etc/container_enrichment.lua:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro

  cloudflare:
    image: cloudflare/cloudflared:latest
    container_name: club_cloudflare
    restart: unless-stopped
    networks:
      - club_network
    env_file:
      - /home/deploy/cloudflare/.env
    command: tunnel --no-autoupdate run
    volumes:
      - /home/deploy/cloudflare/cloudflared:/etc/cloudflared
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "3"

networks:
  club_network:
    driver: bridge