sources:
  docker_logs:
    type: docker_logs
    include_containers:
      - "club_app"
      - "club_queue" 
      - "club_postgres"
    include_labels:
      - "com.docker.compose.service"
    auto_partial_merge: true
    partial_event_marker_field: "_partial"

transforms:
  parse_logs:
    type: remap
    inputs:
      - docker_logs
    source: |
      # Add environment and source metadata
      .environment = "staging"
      .source = "docker"
      # Ensure timestamp consistency
      .@timestamp = now()

sinks:
  http_output:
    type: http
    inputs:
      - parse_logs
    uri: "https://${OO_HOST}:${OO_PORT}/api/${OO_ORG}/${OO_STREAM}/_json"
    method: post
    auth:
      strategy: basic
      user: "${OO_USER}"
      password: "${OO_PASS}"
    encoding:
      codec: json
    compression: gzip
    batch:
      max_events: 100
      timeout_secs: 5
    request:
      headers:
        Content-Type: "application/json"